# This workflow is a trial workflow for Python

name: Scheduled and Push Trigger

on: 
#  schedule:
#  - cron: '2 */2 * * *'
  push:
    
env:
  DEVOPS_DIR: Myrepo

jobs:
  run_workflow:
    name: My_First_Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Check-out Myrepo repository
      uses: actions/checkout@v2
      with:
        repository: pramodsurve/Branch_Trial_Repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Python Packages
      run:
        python -m pip install pandas datetime

    - name: Run Python Script
      run: python Test.py
      shell: sh
