# This workflow is a trial workflow for Python

name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: First_Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: pramodsurve/Branch_Trial_Repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Pandas
      run:
        python -m pip install pandas
        python -m pip install datetime

    - name: Hello World
      run: python Test.py
      shell: sh
